name: Database API Tests

on:
  push:
    paths:
      - 'tests/**'
      - 'backend/database/**'
      - 'run_tests.sh'
      - '.github/workflows/api-tests.yml'
  pull_request:
    paths:
      - 'tests/**'
      - 'backend/database/**'
      - 'run_tests.sh'
      - '.github/workflows/api-tests.yml'

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    environment: credential


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install -r tests/requirements.txt
      
      - name: Write secrets to .env
        run: |
          echo "DATABRICKS_HTTP_PATH=${{ secrets.DATABRICKS_HTTP_PATH }}" >> backend/app/.env
          echo "DATABRICKS_SERVER_HOSTNAME=${{ secrets.DATABRICKS_SERVER_HOSTNAME }}" >> backend/app/.env
          echo "DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN }}" >> backend/app/.env

      - name: Start backend server
        run: |
          cd backend/app
          nohup python main.py &
        shell: bash

      - name: Wait for backend to be ready
        run: |
          for i in {1..10}; do
            if curl -s http://127.0.0.1:5000/db/users > /dev/null; then
              echo "Backend is up!"
              exit 0
            fi
            sleep 2
          done
          echo "Backend did not start in time" >&2
          exit 1

      - name: Run API tests
        run: |
          chmod +x run_tests.sh
          ./run_tests.sh
